04-MVC-Views-Part-2/MVCModels.Web/Models/ErrorViewModel.cs
using System;

namespace MVCModels.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

04-MVC-Views-Part-2/MVCModels.Web/Models/Ingredient.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCModels.Web.Models
{
    public class Ingredient
    {
        /// <summary>
        /// Name of the ingredient
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Quantity of the ingredient in the recipe
        /// </summary>
        public string Quantity { get; set; }
    }
}

04-MVC-Views-Part-2/MVCModels.Web/Models/Recipe.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCModels.Web.Models
{
    public class Recipe
    {
        public int Id { get; set; }

        /// <summary>
        /// Name of the recipe
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Description of the recipe
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// The image name for the recipe
        /// </summary>
        public string ImageName { get; set; }

        /// <summary>
        /// Ingredients in the recipe
        /// </summary>
        public List<Ingredient> Ingredients { get; set; } = new List<Ingredient>();

        /// <summary>
        /// Steps for preparing the recipe
        /// </summary>
        public List<string> PreparationSteps { get; set; } = new List<string>();

        /// <summary>
        /// Average rating of the recioe
        /// </summary>
        public double AverageRating { get; set; }

        /// <summary>
        /// Approx. time in minutes to cook
        /// </summary>
        public int CookTimeInMinutes { get; set; }

        /// <summary>
        /// Type of recipe
        /// </summary>
        public string RecipeType { get; set; }
    }
}

04-MVC-Views-Part-2/MVCModels.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVCModels.Web.Models;

namespace MVCModels.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }     

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

04-MVC-Views-Part-2/MVCModels.Web/Controllers/RecipesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVCModels.Web.DAL;
using MVCModels.Web.Models;

namespace MVCModels.Web.Controllers
{
    public class RecipesController : Controller
    {        
        // GET: recipes/
        // GET: recipes/index
        public IActionResult Index()
        {
            IRecipeDAL dal = new MockRecipeDAL();
            IList<Recipe> recipes = dal.GetRecipes(); 

            return View(recipes);
        }

        // GET: recipes/table
        public IActionResult Table()
        {
            IRecipeDAL dal = new MockRecipeDAL();
            IList<Recipe> recipes = dal.GetRecipes();

            return View(recipes);
        }

        // GET: recipes/detail/1
        // GET: recipes/detail/3
        // GET: recipes/detail?id=1
        // GET: recipes/detail?id=3
        public IActionResult Detail(int id = 1)
        {
            IRecipeDAL dal = new MockRecipeDAL();
            Recipe recipe = dal.GetRecipe(id);

            return View(recipe);
        }
    }
}

04-MVC-Views-Part-2/MVCModels.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

04-MVC-Views-Part-2/MVCModels.Web/Views/Recipes/Detail.cshtml
@model Recipe
@{
    ViewData["Title"] = "Detail";
}
<html>
<head>
    <title></title>
    <style>

        div > img {

            float: left;
            padding-right: 10px;

        }

        .imgIntro {

            width: 100%;
            display: block;
            padding-bottom: 90px;

        }

    </style>


</head>
<body>


    <h2 style="font-size: 30px">Detail</h2>
    <div class="imgIntro ">
        <img src="/../../images/@Model.ImageName" height="250" width="300" />

        <div class="intro">

            <p style="font-size: 25px">@Model.Name</p>
            <p>@Model.RecipeType</p>
            <span style="font-weight: bold">Cook Time </span><span>@Model.CookTimeInMinutes minutes</span><span><br /></span>
                                                             
            <p>@Model.Description</p>

        </div>
    </div>

    

    <div>
        <h3 style="font-size: 30px">Ingredients</h3>
        <ul>
            @foreach (Ingredient ingredients in Model.Ingredients)
            {
                <li>@ingredients.Quantity @ingredients.Name</li>
            }


        </ul>

    </div>

    <div class="prep">

        <h4 style="font-size: 30px">Preparation</h4>
        <ol>
            @foreach (string prepItem in Model.PreparationSteps)
            {
                <li>@prepItem</li>
            }
        </ol>
    </div>

</body>
</html>

04-MVC-Views-Part-2/MVCModels.Web/Views/Recipes/Index.cshtml
@model IList<Recipe>

@{
    ViewData["Title"] = "Index";
}
<html>
<head>
    <style>
        .wrapper {
            display: grid;
            grid-gap: 10px;
            margin: 10px;
            grid-template-rows: 1fr;
            grid-template-columns: repeat(3, 300px);
            justify-content: center;
        }

        .item {
            background-color: lightgreen;
            height: 350px;
            vertical-align: middle;
        }

        h1 {
            position: relative;
            bottom: 5px;
            padding-left: 3px;
            color: blue;
            font-weight: bold;
            font-size: 16px;
        }

        .bottomalign {
            /*position: relative;
            bottom: 10px;*/
            display: inline-block;
            margin: auto;
        }

        .bottomaligntext {
            /*position: relative;*/
            display: inline-block;
            text-align: right;
            margin: auto;
        }
    </style>
</head>

<h2>Index</h2>
<div class="wrapper">
    @foreach (Recipe recipe in Model)
    {
        <div class="item">
            <a asp-controller="Recipes" asp-action="Detail" asp-route-id="@recipe.Id">
                <img src="/../../images/@recipe.ImageName" height="250" width="300" />
            </a>
                <a asp-controller="Recipes" asp-action="Detail" asp-route-id="@recipe.Id">
                    <h1>@recipe.Name</h1>
                </a>
                @switch (Math.Round(recipe.AverageRating, 0))
                {
                    case 1:
                        <img src="/../../images/1-star.png" height="20" width="80" class="bottomalign" /> 
                        break;
                    case 2:
                        <img src="/../../images/2-star.png" height="20" width="80" class="bottomalign" />
                        break;
                    case 3:
                        <img src="/../../images/3-star.png" height="20" width="80" class="bottomalign" />
                        break;
                    case 4:
                        <img src="/../../images/4-star.png" height="20" width="80" class="bottomalign" />
                        break;
                    case 5:
                        <img src="/../../images/5-star.png" height="20" width="80" class="bottomalign" />
                        break;
                }
                <p class="bottomaligntext">@recipe.Ingredients.Count Ingredients</p>


</div>
    }

</div>

04-MVC-Views-Part-2/MVCModels.Web/Views/Recipes/Table.cshtml
@model IList<Recipe>
@{
    ViewData["Title"] = "Table";
}

<h2>Table</h2>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <style>

        .item1 {
            display: inline-block;
            padding-right: 50px;
        }
        .item2 {
            display: inline-block;
            width: 325px;
            height: 450px;
        }

        .text1{
            text-align: center;
        }

    </style>
    <title></title>
</head>
<body>

    <div class="item1">
        <p>Name</p>
        <p>Type</p>
        <p>Cook Time</p>
        <p>Ingredients</p>
        <p>Rating</p>
    </div>


    @foreach (Recipe recipe in Model)
    {
        <div class="item2">
            <div class="text1">
                <a asp-controller="Recipes" asp-action="Detail" asp-route-id="@recipe.Id">
                    <img src="/../../images/@recipe.ImageName" height="125" width="150" /> </a>
                <a asp-controller="Recipes" asp-action="Detail" asp-route-id="@recipe.Id">
                    <p>@recipe.Name</p> </a>
                    <p>@recipe.RecipeType</p>
                    <p>@recipe.CookTimeInMinutes min</p>
                    <p>@recipe.Ingredients.Count ingredients</p>
                    @switch (Math.Round(recipe.AverageRating, 0))
                    {
                        case 1:
                            <img src="/../../images/1-star.png" height="20" width="90" class="bottomalign" />
                            break;
                        case 2:
                            <img src="/../../images/2-star.png" height="20" width="90" class="bottomalign" />
                            break;
                        case 3:
                            <img src="/../../images/3-star.png" height="20" width="90" class="bottomalign" />
                            break;
                        case 4:
                            <img src="/../../images/4-star.png" height="20" width="90" class="bottomalign" />
                            break;
                        case 5:
                            <img src="/../../images/5-star.png" height="20" width="90" class="bottomalign" />
                            break;
                    }
</div>
        </div>
    }
    </body>
</html>

04-MVC-Views-Part-2/MVCModels.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCModels.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">MVC Models</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="Recipes" asp-action="Index">Recipes</a></li>
                </ul>
            </div>
        </div>
    </nav>    

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Tech Elevator</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>